<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
	<xacro:include filename="$(find riser_robot_description)/urdf/inertials.xacro"/>
	<xacro:macro name="leg" params="name parent *leg_origin holder_length holder_radius pipe_length pipe_radius">

	<xacro:property name="holder_weight" value="0.5" />
	<xacro:property name="pipe_weights" value="0.25" />
	<xacro:property name="pi" value="3.1415" />
	<!-- LINKS -->
	<link name="${name}_leg_link">
		<pose>0 0 0 0 0 0</pose>
		<xacro:cylinder_inertial mass="${holder_weight}" radius="${holder_radius}" length="${holder_length}"/>
		<collision>
			<origin rpy="0 0 0" xyz="0 0 0"/>
			<geometry>
		  	<cylinder length="${holder_length}" radius="${holder_radius}"/>
			</geometry>
		</collision>
		<visual>
			<origin rpy="0 0 0" xyz="0 0 0"/>
		  <geometry>
		  	<cylinder length="${holder_length}" radius="${holder_radius}"/>
		  </geometry>
	  </visual>
  </link>
  
  <link name="${name}_upper_pipe">
		<pose>0 0 0 0 0 0</pose>
		<xacro:cylinder_inertial mass="${pipe_weights}" radius="${pipe_radius}" length="${pipe_length}"/>
		<collision>
			<origin rpy="0 0 0" xyz="0 0 0"/>
			<geometry>
		  	<cylinder length="${pipe_length}" radius="${pipe_radius}"/>
			</geometry>
		</collision>
		<visual>
			<origin rpy="0 0 0" xyz="0 0 0"/>
		  <geometry>
		  	<cylinder length="${pipe_length}" radius="${pipe_radius}"/>
		  </geometry>
	  </visual>
  </link>
  
  <link name="${name}_lower_leg_link">
		<pose>0 0 0 0 0 0</pose>
		<xacro:cylinder_inertial mass="${holder_weight}" radius="${holder_radius}" length="${holder_length}"/>
		<collision>
			<origin rpy="0 0 0" xyz="0 0 0"/>
			<geometry>
		  	<cylinder length="${holder_length}" radius="${holder_radius}"/>
			</geometry>
		</collision>
		<visual>
			<origin rpy="0 0 0" xyz="0 0 0"/>
		  <geometry>
		  	<cylinder length="${holder_length}" radius="${holder_radius}"/>
		  </geometry>
	  </visual>
  </link>
	
	<!-- JOINTS -->
	<joint name="${name}_leg_joint" type="fixed">
			<child link="${name}_leg_link"/>
			<parent link="${parent}"/>
			<xacro:insert_block name="leg_origin" />
	</joint>
	
	<joint name="${name}_upper_pipe_joint" type="fixed">
			<child link="${name}_upper_pipe"/>
			<parent link="${name}_leg_link"/>
			<origin xyz="0 -${holder_radius/2 + pipe_length/2} 0" rpy="-${pi/2} 0 0"/>
	</joint>
	
	<joint name="${name}_lower_leg_joint" type="fixed">
			<child link="${name}_lower_leg_link"/>
			<parent link="${name}_upper_pipe"/>
			<origin xyz="0 -${holder_radius/2 + pipe_length/2} 0" rpy="-${pi/2} 0 0"/>
	</joint>
	
	</xacro:macro>
</robot>
